apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
  namespace: argo
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: seldon-app
            operator: In
            values:
            - online-inference-single-online-inference-single
        topologyKey: kubernetes.io/hostname
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
