apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: python
  namespace: argo
spec:
  activeDeadlineSeconds: 3600
  affinity:
    pod_anti_affinity:
      required_during_scheduling_ignored_during_execution:
        label_selector:
          - match_expressions:
              - key: seldon-app
                operator: In
                values:
                  - online-inference-single-online-inference-single
        topology_key: kubernetes.io/hostname
  entrypoint: python
  serviceAccountName: argo
  templates:
    - name: python
      steps:
        - - name: module-87
            template: module
    - name: module
      container:
        image: debian:latest
        command:
          - sh
          - -c
          - 'echo "running"; exit 0'
  ttlSecondsAfterFinished: 5400.0
